### ISSUE TITLE
Simulation events not deleted, "clear events" not working

### ISSUE THREAD

**Issue by phihei** [cpn-io/cpn-js#304]
Hi, 
I'm very happy to use CPN IDE. I found some minor bugs while playing around. 
One that bugs me: after starting a simulation and recording the events, and starting a second simulation afterwards, the play-out recorded events option will save events from both simulations to file. 
Only workaround so far (since I did not find any tmp/ cache file in AppData) is to close and restart the IDE

**Comment by hmwverbeek** [comment]
Is fixed by earlier commit.
