### ISSUE TITLE
Adding declarations in the declaration panel when having moved to another tab creates declarations in the previously selected tab

### ISSUE THREAD

**Issue by I-Doroshkevich** [cpn-io/cpn-js#49]
In declaration panel after moving to another tab clicking on **+New** (before selecting any declaration already existing in this tab) creates a new declaration in the previously edited tab.  Wouldn't it be better to forbid adding a declaration to the previously edited tab right away after having moved to another tab?

**Comment by dfahland** [comment]
Fixed/obsolete by new decalaration panel.
