### ISSUE TITLE
Electron/Back-end: closing the Electron backend-end leaves ML simulator sometimes running 

### ISSUE THREAD

**Issue by dfahland** [cpn-io/cpn-js#59]
The back-end launches an instance of the CPN ML simulator process. This process sometimes remains in memory even after back-end process has terminated. This may sometime prevent correct operation of a new back-end process (as the back-end process cannot create a new CPN ML simulator instance). The issue lies in Access/CPN but affects the back-end.

Not sure how handle this. Can the CPN ML simulator instances spawned by Access/CPN be terminated when closing the back-end?

**Comment by sergey-egorov** [comment]
> Not sure how handle this. Can the CPN ML simulator instances spawned by Access/CPN be 
> terminated when closing the back-end?
Closing app window will terminate back-end and all ML simulator instances
