### ISSUE TITLE
IDE: Meaning of "Reload" is unclear

### ISSUE THREAD

**Issue by dfahland** [cpn-io/cpn-js#70]
User feedback: It does not reload the file from disk (if you delete monitors for example, they are not reloaded), but it also does not reload the UI from the simulator (if you make them inconsistent as in BvD12, the model is not reloaded). It seems as if "Reload" does the same as "Validate"?

For a user in the Electron-based version, the word "reload" is associated to "reload file from disk".

**Comment by sergey-egorov** [comment]
It was debug functionality, now it's hidden
