### ISSUE TITLE
No suggestion/auto-completion when editing colorset-annotation of places

### ISSUE THREAD

**Issue by I-Doroshkevich** [cpn-io/cpn-js#84]
RQ-23. f.ii

Suggestion/auto-completion (based on name) when editing colorset-annotation of places is not provided.

**Comment by dfahland** [comment]
No auto-completion when editing colorset annotation in model canvas.

**Comment by dfahland** [comment]
Auto-Completion should also work when editing the label in the editing canvas.
![image](https://user-images.githubusercontent.com/3033974/100712219-af1c6100-33b2-11eb-91ac-04436fb17e70.png)

**Comment by sasha4052** [comment]
Please give more details for this bug.
Default value when focusing on an empty label (UNIT in this case) is not Auto-Completion?
